### ISSUE TITLE
ThreadedModel async loading

### ISSUE THREAD

**Issue by danomatika** [zkmkarlsruhe/ofxTensorFlow2#1]
The ofxTF2::ThreadedModel inherits the `load()` function from ofxTF2::Model which is a simple, blocking load. On slower systems, this can be relatively expensive as it will generally happen on the main thread.

We could look into adding asynchronous model loading on the background thread, possibly by an additional `loadAsync()` function.

**Comment by bytosaur** [comment]
added in [1.1.0](https://github.com/zkmkarlsruhe/ofxTensorFlow2/releases/tag/1.1.0)
