### ISSUE TITLE
off topic model issue

### ISSUE THREAD

**Issue by liquidzym** [zkmkarlsruhe/ofxTensorFlow2#14]
i'm using 060_hair_segmentation model which is download from https://github.com/PINTO0309/PINTO_model_zoo/tree/main/060_hair_segmentation/10_tftrt
got those errors during the loading 

SavedModel load for tags { serve }; Status: fail: Not found: Op type not registered 'CreateTRTResourceHandle' in binary running on SLDEV. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.. Took 175474 microseconds.

any ideas? since i'm not familiar with those model conversion stuff,any hints would be appreciated!

**Comment by bytosaur** [comment]
hey sorry i have no experience with tensorRT. Do you have it installed and to tried to load the model in python?

**Comment by danomatika** [comment]
Should we close?

**Comment by liquidzym** [comment]
sorry, i'll let you know once i got time to testing it, let's close it for now,thank you!
