### ISSUE TITLE
"Undefined symbols for architecture arm64:   "_TF_NewSessionOptions", referenced from:" on macOS ?

### ISSUE THREAD

**Issue by stephanschulz** [zkmkarlsruhe/ofxTensorFlow2#15]
Hi.
Thanks for make this addon available to us.

I am on macOS 10.15.7, OF 0.11.2m Xcode 12.4

I followed the macOS install steps and get a bunch of compile errors related to `arm64`

Would you know why?
Should I rather try OF 0.11.0 ?
Should I be on a more recent macOS?

```
Undefined symbols for architecture arm64:
  "_TF_NewSessionOptions", referenced from:
      cppflow::model::model(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in ofxTF2Model.o
  "_TF_NewBufferFromString", referenced from:
      cppflow::model::model(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in ofxTF2Model.o
  "_TF_NewGraph", referenced from:
      cppflow::model::model(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in ofxTF2Model.o
  "_TF_DeleteSessionOptions", referenced from:
      cppflow::model::model(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in ofxTF2Model.o
  "_TF_GraphNextOperation", referenced from:
      cppflow::model::get_operations() const in ofxTF2Model.o
  "_TF_GraphGetTensorNumDims", referenced from:
      cppflow::model::get_operation_shape(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in ofxTF2Model.o
  "_TF_OperationName", referenced from:
      cppflow::model::get_operations() const in ofxTF2Model.o
  "_TF_GraphOperationByName", referenced from:
      cppflow::model::operator()(std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, cppflow::tensor>, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, cppflow::tensor> > >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >) in ofxTF2Model.o
      cppflow::model::get_operation_shape(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in ofxTF2Model.o
  "_TF_SessionRun", referenced from:
```

<img width="1415" alt="Screen Shot 2022-01-17 at 2 10 11 PM" src="https://user-images.githubusercontent.com/1054816/149825834-76278274-5275-42d8-90af-77a9fcfda0ea.png">
<img width="1395" alt="Screen Shot 2022-01-17 at 2 09 50 PM" src="https://user-images.githubusercontent.com/1054816/149825842-d0c9eac6-1e1b-43ca-9a22-c3ec89b3d414.png">
<img width="1402" alt="Screen Shot 2022-01-17 at 2 09 27 PM" src="https://user-images.githubusercontent.com/1054816/149825844-91446b55-bb57-474e-ae35-e6739907cc4b.png">

**Comment by stephanschulz** [comment]
I changing `VER=2.6.0` to `VER=2.7.0` in this line:
https://github.com/zkmkarlsruhe/ofxTensorFlow2/blob/main/scripts/download_tensorflow.sh#L12

seems to solve this.

**Comment by danomatika** [comment]
libtensorflow builds for mac are currently x86_64 only. Most likely, you need to add arm64 to the Xcode projects' excluded architectures and rebuild.

**Comment by stephanschulz** [comment]
I am on a MacBook Pro 2.3 GHz 8-Core Intel Core i9.
Simply switching to `VER=2.7.0` did the trick. 

For reference what my project build target shows for `Architecture` 
<img width="1399" alt="Screen Shot 2022-01-17 at 2 44 36 PM" src="https://user-images.githubusercontent.com/1054816/149829191-9b0bccd1-7770-48c3-9f86-45dbbbce97b5.png">
<img width="1390" alt="Screen Shot 2022-01-17 at 2 44 20 PM" src="https://user-images.githubusercontent.com/1054816/149829194-1581feec-237e-4c30-a86a-b6ef27be805c.png">
<img width="1115" alt="Screen Shot 2022-01-17 at 2 46 38 PM" src="https://user-images.githubusercontent.com/1054816/149829314-86a98edc-fa1c-405c-b795-a2a7334c86fa.png">

Thanks again for making TensorFlow accessible to OF

**Comment by stephanschulz** [comment]
Actually I ma now noticing that it builds fine in Debug mode but gives the first reported errors for Release mode.

**Comment by stephanschulz** [comment]
and you are correct that adding `arm64`to the excluded architectures solved the issue also for Release mode.

**Comment by danomatika** [comment]
We are considering providing builds for macOS arm64 and I know there are some unofficial builds on GitHub, but they are out of date. I'm still a bit surprised there aren't official universal builds yet, but I guess none on the TF team uses macOS.
