### ISSUE TITLE
Do you have plans to implement 3d skeleton detection via BlazePose?

### ISSUE THREAD

**Issue by stephanschulz** [zkmkarlsruhe/ofxTensorFlow2#17]
I just came across this post, [3D Pose Detection with MediaPipe BlazePose GHUM and TensorFlow.js](https://blog.tensorflow.org/2021/08/3d-pose-detection-with-mediapipe-blazepose-ghum-tfjs.html).
Do you have plans to make an example on how to use this library. I think it's TF.js pose-detection API ?

As always thank you for your efforts to make tensor flow accessible to the OF community.

**Comment by bytosaur** [comment]
hey @stephanschulz,

I dont think that we will expand this addon to work with MediaPipe as it comes with new dependencies. This addon only suffices running the functions given by the C library which is only a subset of the functions in the python library.

MediaPipe has a lot of tf.js models which might be converted.
Check out [their tfhub section](https://tfhub.dev/s?publisher=mediapipe), but be careful as a some applications require some code from the mediapipe library in between two models. E.g. hand tracking requires palm detection + mediapipe lib calls + handpose...

I didnt look too much into MediaPipe, but most models are available in C++. To fully make use of MediaPipe you would want to build the examples in an openFrameworks way (i guess without bazel ?). Then publish that as a standalone addon.

**Comment by danomatika** [comment]
Yeah, I could imagine something like an addon for MediaPipe models which uses ofxTensorFlow2 as a dependency, but it's not something we will probably get into on our end.

**Comment by stephanschulz** [comment]
Thanks for the input and advice.
Implementing this is currently beyond my skills. But it's a great road map to follow.

**Comment by danomatika** [comment]
Closing for now.
