### ISSUE TITLE
trained model different format?

### ISSUE THREAD

**Issue by paul-ferragut** [zkmkarlsruhe/ofxTensorFlow2#22]
I managed to train a model for pix2pix, however the output files are looking different than the included edge2shoe example.
<img width="472" alt="2022-06-19 22_49_18-C__Users_plesk_Documents_coding_of_v0 11 2_vs2017_release_addons_ofxTensorFlow2_" src="https://user-images.githubusercontent.com/904819/174499985-5ac3fd6a-9508-403d-8501-bd44380b7ea5.png">
I don't have `assets `and `variables `folder and no `.pb` file. I would appreciate some more guidance for how to format my trained model so I can use it with the example.

**Comment by bytosaur** [comment]
hey @paul-ferragut,

how did you train it ? Did you use the original repo or the one I put into the examples folder?
my version has a main.py which calls [this source file](https://github.com/zkmkarlsruhe/ofxTensorFlow2/blob/main/example_pix2pix/python/src/training.py). Line 136 writes a model after every epoch to ''../bin/data/", which is the folder where the model should be for the openFrameworks. Please check the location ;)

**Comment by bytosaur** [comment]
okok please check the README in the python folder ;)

**Comment by paul-ferragut** [comment]
Can I change the script to train with my own local dataset instead of the existing downloadable datasets?
In the python folder I have a folder 'combined' with my formatted images in a subfolder train and val.
in `main.py` I tried to change 
```
# In[4]:
path = "combined/" #download_existing_dataset(EXISTING_DATASETS[DATASET], DATASET)
print('Dataset Path ->', path)
```
thank you!

**Comment by bytosaur** [comment]
From the first look it seems to be as easy as that... I would simply try to use as much of the folder structure, image properties and code as the original script. Image properties might be the one you will struggle with most. If needed I would write a separate script that transforms your data

**Comment by paul-ferragut** [comment]
thank you for the help @bytosaur I got everything working :)
Should have read the readme better .
Now I will have some fun testing datasets :) A last question, do you have a recommendation for number of epochs?
