### ISSUE TITLE
Yolo v4 example

### ISSUE THREAD

**Issue by Jonathhhan** [zkmkarlsruhe/ofxTensorFlow2#26]
I posted it already in the OF forum. Here is a Yolo v4 example: https://forum.openframeworks.cc/t/yolo-v4-example-with-ofxtensorflow2/40040

**Comment by bytosaur** [comment]
ah ok didnt see that but I figured it out anyway :P
update coming soon.

**Comment by Jonathhhan** [comment]
Haha, nice. Funny that we uploaded it the same day :)
And you are using the same non-maximum suppression library.

**Comment by Jonathhhan** [comment]
Here I calculate the bounding boxes directly with cppflow:
https://github.com/Jonathhhan/ofxTensorFlow2/blob/example_yolo_v4/example_yolo_v4_v2

**Comment by danomatika** [comment]
I wouldn't render the bounding boxes into the output image. What if you want to style them differently, use them as masks, etc. This is better done in OF as with the previous version of the example.

**Comment by danomatika** [comment]
I am currently doing a refactor of the currently merged example. Once I'm father along, we can look into updating/integrating any new changes.

**Comment by Jonathhhan** [comment]
@danomatika alright :) and i had a similar feeling with the bounding boxes and changed it accordingly (not render them into the image)...

**Comment by danomatika** [comment]
@Jonathhhan Also, the example is missing the input image. Can you include it, either in the v2 example or as a separate PR to our `feature/examples` branch?

**Comment by danomatika** [comment]
Thanks for the update. It's good to use the cppflow nms implementation since it's built in. I have also refactored the model handling into a separate class as I found it pretty complicated on it's own within the ofApp.

Please check the current version of the example in the `feature/new_examples` branch.

**Comment by bytosaur** [comment]
included in #29

**Comment by danomatika** [comment]
Just a note: I took the updated example as used it as a basis for a new YoloOSC app: https://github.com/zkmkarlsruhe/YoloOSC

Like FaceOSC, it streams detected objects over OSC (and the camera image via Spyhon on macOS). Thanks again, you are listed as one of the source authors.

**Comment by Jonathhhan** [comment]
@danomatika Yes, I also guess the full name is the best. Was just choosing Jonathhhan because Jonathan was not available anymore. Thanks.

**Comment by danomatika** [comment]
Done. Thanks
