### ISSUE TITLE
Stable diffusion or other text-to-image networks?

### ISSUE THREAD

**Issue by Jonathhhan** [zkmkarlsruhe/ofxTensorFlow2#32]
I wonder if it is possible to implement stable diffusion or any other text-to-image network (dall-e for example).
https://github.com/CompVis/stable-diffusion
I guess, the complicated part is the pre-/postprocessing and converting the model to a saved_model...
Any hints are very welcome...

**Comment by bytosaur** [comment]
hey,
I dont know how difficult it is to port the code, but I dont think you would gain a lot from running it with openFrameworks other than comfort. I am running the repository on our server and infering the standard text-to-image pipeline ([diffusers](https://github.com/huggingface/diffusers/)) takes about 3 seconds.  Therefore, you could easily run it with python (e.g. REST API) and accept a little latency. Nevertheless, many people would happily use it in ofxTensorFlow2...

**Comment by Jonathhhan** [comment]
Here is my attempt (one year later - and actually without ofxTensorFlow2): https://forum.openframeworks.cc/t/stable-diffusion-example/42488

**Comment by danomatika** [comment]
Ja with a C++ wrapper, Tensorflow is not really needed ala whisper.cpp or lama.cpp. Cool that this is available now.

**Comment by danomatika** [comment]
I am closing this for now. There are runners available for this model and, as @bytosaur mentions, it's probably better to use their web API to send prompts and grab generated images.

**Comment by Jonathhhan** [comment]
Just wantes to mention, that I made an addon for that: https://github.com/Jonathhhan/ofxStableDiffusion
