### ISSUE TITLE
Compilation issues for M1 / arm64

### ISSUE THREAD

**Issue by golanlevin** [zkmkarlsruhe/ofxTensorFlow2#33]
Hi friends, 
I'm having M1-architecture-related linking problems ("Undefined Symbol" etc.) similar to those described in Issues #15 and #3. I have tried the posted fixes without luck, and also (possibly) discovered a problem with one of the scripts. My configuration is:  

* Hardware: MacBook Pro (14-inch, 2021) with Apple M1 Pro.
* Software: OSX 12.6, XCode 14.0.1 (14A400).
* Building within a fresh copy of of_v0.11.2_osx_release.  

I have followed the posted instructions as follows:
* I did the downloads: I cloned https://github.com/zkmkarlsruhe/ofxTensorFlow2.git to OFROOT/addons; I pulled & checked-out cppflow to ofxTensorFlow2/libs/cppflow (using `git submodule update --init --recursive`); and I downloaded the models using ./scripts/download_example_models.sh.
* I'm pretty certain that I'm using c++14. I updated `CLANG_CXX_LANGUAGE_STANDARD = c++14` suchly in CoreOF.xcconfig. I also updated `PLATFORM_CXXFLAGS += -std=c++14` suchly at line 142 of config.osx.default.mk. 
* I used download_tensorflow.sh to install libtensorflow.2.8.0 in ofxTensorFlow2/libs/tensorflow/. As expected, these x86_64 libraries didn't work; so, I then replaced the contents of the ofxTensorFlow2/libs/tensorflow/ directory with the "unofficial" arm64 materials from https://github.com/vodianyk/libtensorflow-cpu-darwin-arm64.
* I created the project example_video_matting.xcodeproj using the Project generator
* In the Build Phases for this project's target, in the 2nd Run Script, I added the following before the final echo line: `$OF_PATH/addons/ofxTensorFlow2/scripts/macos_install_libs.sh "$TARGET_BUILD_DIR/$PRODUCT_NAME.app";`
* As recommended, I set _Build Settings->Excluded Architectures_ to "x86_64" for the Project. (For good measure, I also tried every combination of arm64/x86_64 libraries with excluding each architecture, since there is seemingly contradictory advice about which architectures to exclude [here](https://github.com/zkmkarlsruhe/ofxTensorFlow2#building-for-x86_64-on-an-apple-silicon-system) and [here](https://github.com/zkmkarlsruhe/ofxTensorFlow2/issues/3#issuecomment-1023049785))
* I cleaned the build folder before trying to (re)build.

Unfortunately, I'm still getting Undefined Symbols for all of the Tensorflow stuff: 

<img width="1175" alt="Screen Shot 2022-10-01 at 3 43 45 AM" src="https://user-images.githubusercontent.com/290053/193399146-d3146ac6-9474-4ac5-91e4-65081aaa2c90.png">

I feel like I'm close, but I'm out of ideas for how to get further. Thanks so much for any help. 

**Side Note 1:** The ofxTensorFlow2 script, `configure_xcode.sh`, appears to be corrupting XCode 14 projects. After I run this script, .xcodeproj files no longer open, and XCode reports the error: "_The project ‘example_video_matting’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts._"

**Side Note 2:** FWIW, [TensorFlow.org](https://www.tensorflow.org/install/lang_c) is now offering version 2.9.1 for download (though, there is no indication that it works for arm64).

**Comment by danomatika** [comment]
For future reference, the issue was caused by the libs not being in a folder named for the system / build environment:

~~~
libs/tensorflow/lib/*.dylibs <-- WHY U NO WORK?!
libs/tensorflow/lib/osx/*dylibs <-- WORK
~~~

This is a subtle issue that the download script handles for you but easy to miss if doing things manually, especially considering the downloaded library structure is very similar.

I've updated the README to clarify this point (under [Dependencies](https://github.com/zkmkarlsruhe/ofxTensorFlow2#dependencies)) as well as smoothed over some other workflow details on macOS. The updated info is mainly in this commit: 4e4866e16cc3ac1a2910479a0aa592f17386a2a2

**Comment by golanlevin** [comment]
Thanks, @danomatika, for your incredibly helpful advice. It works like a charm. Having the Zoom-quality body segmentation of ofxTensorflow2 (in arbitrary scenes!), in an open-source arts toolkit like openframeworks is simply astounding. I would have killed for this 20 years ago. Kudos to you, @zkmkarlsruhe, and all the other contributors for making this possible.

<img width="1280" alt="Screen Shot 2022-10-01 at 11 11 27 PM" src="https://user-images.githubusercontent.com/290053/193436643-cbe2dd1d-aa4f-4e7a-a3f8-506274cf53a5.png">

**Comment by danomatika** [comment]
Thanks for the kinds words, Golan! Nice to get a feedback bump.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com
