### ISSUE TITLE
error: Signing Identity: “-”

### ISSUE THREAD

**Issue by stephanschulz** [zkmkarlsruhe/ofxTensorFlow2#37]
I had this addon working successfully with OF 11.2 on a previous macOS system.
now I am on a M1 with macOS 12.6.8 and Xcode 14.1.0 and get these 2 errors:

```
CodeSign /Applications/of_v0.12.0_osx_release/addons/ofxTensorFlow2/example_video_matting/bin/example_video_mattingDebug.app/Contents/MacOS/libtensorflow_framework.dylib (in target 'example_video_matting' from project 'example_video_matting')
    cd /Applications/of_v0.12.0_osx_release/addons/ofxTensorFlow2/example_video_matting
    
    Signing Identity:     "-"
    
    /usr/bin/codesign --force --sign - --deep --timestamp\=none --preserve-metadata\=identifier,entitlements,flags --generate-entitlement-der /Applications/of_v0.12.0_osx_release/addons/ofxTensorFlow2/example_video_matting/bin/example_video_mattingDebug.app/Contents/MacOS/libtensorflow_framework.dylib

/Applications/of_v0.12.0_osx_release/addons/ofxTensorFlow2/example_video_matting/bin/example_video_mattingDebug.app/Contents/MacOS/libtensorflow_framework.dylib: main executable failed strict validation
Command CodeSign failed with a nonzero exit code
```

The .dylib is in the right place
![Screen Shot 2024-02-15 at 5 50 22 PM](https://github.com/zkmkarlsruhe/ofxTensorFlow2/assets/1054816/0f669874-49c8-42b5-928c-5f25f43d27cf)
and I think it has the right permissions
![Screen Shot 2024-02-15 at 5 51 00 PM](https://github.com/zkmkarlsruhe/ofxTensorFlow2/assets/1054816/21175cf3-b09f-442c-8576-69a82654b57a)

and then the main issue I guess is the `    Signing Identity:     "-"` thing?

the same issue is mentioned but for a different project.
https://github.com/openframeworks/openFrameworks/issues/6705

I am a bit lost. 

other default OF examples compile and run just fine.

**Comment by stephanschulz** [comment]
ah Stephan of the past had the solution all along.
set `Embed Without Signing`
https://forum.openframeworks.cc/t/command-codesign-failed-with-a-nonzero-exit-code-xcode-13-3-1/39814/2
![Screen Shot 2024-02-15 at 6 45 39 PM](https://github.com/zkmkarlsruhe/ofxTensorFlow2/assets/1054816/bdbcf0c7-c119-4f90-8088-0bcd7107bd9f)

**Comment by danomatika** [comment]
This step isn't actually needed, so the files can be removed from the Copy Files build phase since the `macos_install.libs.sh` script installs them. See my answer in #38.

**Comment by danomatika** [comment]
> This step isn't actually needed, so the files can be removed from the Copy Files build phase since the `macos_install.libs.sh` script installs them. See my answer in #38.

Hah, actually this doesn't work as linking will fail without them. IN any case, unchecking the COdeSign boxes in the Copy Files phase works fine. I have updated the readme for ofxTF2 1.5.0.
