### ISSUE TITLE
download_example_models.sh does not work

### ISSUE THREAD

**Issue by Jonathhhan** [zkmkarlsruhe/ofxTensorFlow2#39]
The script for downloading the models does not work:
`mv: cannot stat 'download?path=%2F&files=model_basics.zip': No such file or directory`
It is still possible with the direct link: https://cloud.zkm.de/index.php/s/gfWEjyEr9X4gyY6

**Comment by danomatika** [comment]
This should be fixed in develop. There must have been an update to our NextCloud server which caused this.

**Comment by danomatika** [comment]
Fixed in ofxTF2 1.5.0.
