### ISSUE TITLE
question, tf version 

### ISSUE THREAD

**Issue by natxopedreira** [zkmkarlsruhe/ofxTensorFlow2#6]
Hello

Thanks for that addon, i want to move some python code i had to c++ in oF but i need to get a new machine.
Seems like now is very hard to find a 2080 so i must go for 3080 but this last one seems to work only with cuda 11 and tf > 2.4

Have you tested this addon with that config?

Thank you!!

**Comment by danomatika** [comment]
The current version of TF is 2.4. We will updated to 2.5 soon.

Personally, I cannot say much about configurations but if it runs TF2, then it should work with this add-on as the addon-on is simply a wrapper.

**Comment by danomatika** [comment]
Also, you can try TF 2.5 yourself. Edit the version number in `scripts/download_tensorflow.sh` and re-run the script to download. You may need to clean and/or regenerate your project files.

**Comment by natxopedreira** [comment]
If i finally get a 3000 series will do and post results

Im worried about move to 3000 series because tf repo has several issues related, seems like a problem with versions tf+cuda+cudnn, so thats why im asking if you had experience on those cards/config.

Thank you!!!

**Comment by danomatika** [comment]
> seems like a problem with versions tf+cuda+cudnn

I would keep an eye on what they say there. We have a couple MK dev machines, but I don't know the specs and @bytosaur icon vacation. He may respond to this in a week or so.

**Comment by natxopedreira** [comment]
Thank you!!!!

**Comment by bytosaur** [comment]
Hey @natxopedreira ,
sorry for the late response! In my current ofxTensorFlow2 setup I am using a 2070 Super with TF 2.5, Cuda 11.2 and the 460 driver.
I can't guarantee that it will work with 3000er but I am super optimistic!

**Comment by natxopedreira** [comment]
thanks for the update!!

:) im also optimistic, but.... i will try to find a 2080 ti as seems more reliable for now as i need a stable setup and can not wait too much to fix issues.
